default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  user: search_box_user
  password: amazing123

development:
  <<: *default
  database: search_box_db_development

test:
  <<: *default
  database: search_box_db_test
